# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b45fa3d475d89f84ccbb124b98016f8743af0ec3acf1dc3c8105b695999b39c98fe3a9de1ac9d18fbe170f1a070eaa1d2b9572b2ae3f7e8557d37bc1ad304486

test:
  secret_key_base: 6863d2343d50ee04cb13bf3c4e0ef31639015e5924ad8a690c66d27b421bdbc34d64c0749668f0dd7ad83651738f28ef75b5b13c8d10117049f273a2d6adfd45

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
